### ISSUE TITLE
difficults on using scripts

### ISSUE THREAD

**Issue by lebeisean** [zoranbosnjak/asterix-tool#1]
i made my script for changing some properties on cat 010, but where i should put my .py? i cant find the correct place

**Comment by zoranbosnjak** [comment]
So, my understanding is that you want to modify cat010 asterix flow with a custom python script. In this case (suppose the name of your script is `script.py`), you can put the file in any directory. Then you either cd to this directory and run `ast-tool-py custom --script script.py ...` or you provide a path to your script, something like `ast-tool-py custom --script /path/to/script.py ...` .

There is an example on how to run a custom scipt (see *custom filter example*)
https://github.com/zoranbosnjak/asterix-tool/blob/master/ast-tool-py/README.md#running-custom-python-script

**Comment by lebeisean** [comment]
thanks i solved the issue and made the script correctly ! thanks

**Comment by zoranbosnjak** [comment]
Commit comment from 5212f92 contains wrong issue reference.
